apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    prometheus.io/rule: "production-alerts"
  labels:
    prometheus: "production-alerts"
spec:
  replicas: 1
  serviceAccountName: alertmanager
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 2000
  alertmanagerConfigNamespaceSelector: {monitoring: "true"}
  alertmanagerConfigSelector: {k8s}
  configSecret: alertmanager-config
