apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'd75045722@gmail.com'
      smtp_auth_username: 'd75045722@gmail.com'
      smtp_auth_password: 'devops1234'
    route:
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'clement.luc@efrei.net'
        send_resolved: true
        subject: 'CRMM: Alert - {{ .CommonLabels.alertname }}'
        text: '{{ .CommonAnnotations.summary }}'
