apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lb-go-app
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s