apiVersion: apps/v1
kind: development
metadata:
  name: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: development
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
      - name: my-app
        image: my-app:latest
        ports:
        - containerPort: 8081