apiVersion: apps/v1
kind: Deployment
metadata:
  name: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
      - name: my-app-service
        image: my-app:latest
        ports:
        - containerPort: 8081