apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
      - name: my-app-service
        image: sodekai/docker-gs-ping:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
  labels:
    app: development
spec:
  selector:
    app: development
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Port the service listens on
      targetPort: 8081 # Port the container listens on
      nodePort: 30001  # Port exposed on the node (optional, Kubernetes will auto-assign if omitted)
