name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run the Docker image
      docker run --publish 8081:8081 sodekai/docker-gs-ping:latest
    - name: Test the container with curl
      run: |
        sleep 5 # Laisser le temps au conteneur de démarrer
        curl -f http://localhost:8081/whoami || (echo "Test failed" && exit 1)
