name: Kubernetes CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    # Build the Docker image locally
    - name: Build the Docker image
      run: docker build -t my-app:latest .

    # Load the image into Minikube
    - name: Load image into Minikube
      run: |
        minikube start  
        minikube image load my-app:latest

    # Deploy to Development Environment
    - name: Deploy to Development
      run: |
        kubectl apply -f k8s/development.yaml
        sleep 10 # Wait for the deployment to stabilize
        kubectl rollout status deployment/my-app-deployment -n development
    # Test the Development Deployment
    - name: Test Development Deployment
      run: |
        DEVELOPMENT_IP=$(minikube service my-app-service -n development --url)
        curl -f $DEVELOPMENT_IP/whoami || (echo "Development test failed" && exit 1)
  deploy-to-production:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Deploy to Production Environment
    - name: Deploy to Production
      run: |
        kubectl apply -f k8s/production.yaml
        sleep 10 # Wait for the deployment to stabilize
        kubectl rollout status deployment/my-app-deployment -n production
    # Test the Production Deployment
    - name: Test Production Deployment
      run: |
        PRODUCTION_IP=$(minikube service my-app-service -n production --url)
        curl -f $PRODUCTION_IP/whoami || (echo "Production test failed" && exit 1)