name: Kubernetes CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    # Build the Docker image locally
    - name: Build the Docker image
      run: docker build -t my-app:latest .

    # Load the image into Minikube
    - name: Load image into Minikube
      run: |
        minikube start  
        minikube image load sodekai/docker-gs-ping:latest

    # Deploy to Development Environment
    - name: Deploy to Development
      run: |
        kubectl apply -f k8s/development.yaml -n default
        sleep 10 # Wait for the deployment to stabilize

    - name: Test Development Deployment Kubernetes
      run: |

        kubectl get pods

    # Test the Development Deployment
    - name: Test Development Deployment
      run: |
        SERVICE_NAME=$(kubectl get svc -n default -l app=development -o jsonpath='{.items[0].metadata.name}')
        echo "Service Name: $SERVICE_NAME"
    
        DEVELOPMENT_IP=$(minikube service $SERVICE_NAME -n default --url)
        echo "Service URL: $DEVELOPMENT_IP"
        
        # Test the endpoint
        curl -f $DEVELOPMENT_IP/whoami || (echo "Development test failed" && exit 1)
  
  
  deploy-to-production:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Deploy to Production Environment
    - name: Deploy to Production
      run: |
        minikube start
        kubectl apply -f k8s/production.yaml
        sleep 10 # Wait for the deployment to stabilize
        kubectl rollout status deployment/my-app-deployment -n default
    # Test the Production Deployment
    - uses: actions/checkout@v4

    # Install Prometheus and Grafana
    - name: Install Prometheus and Grafana
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
        
        # Install Prometheus
        helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring --create-namespace
        
        # Install Grafana
        helm install grafana grafana/grafana -n monitoring
        
        # Wait for services to start
        sleep 60

    # Configure Prometheus as a Grafana data source
    - name: Configure Grafana
      run: |
        # Get Grafana admin password
        GRAFANA_PASSWORD=$(kubectl get secret -n monitoring grafana -o jsonpath='{.data.admin-password}' | base64 --decode)
        
        # Get Grafana service URL
        GRAFANA_URL=$(minikube service grafana -n monitoring --url)
        
        echo "Grafana URL: $GRAFANA_URL"
        echo "Grafana Admin Password: $GRAFANA_PASSWORD"
        